### ISSUE TITLE
use the example code from README

result

>>> chatbot = Chatbot(token)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/test/venv/lib/python3.11/site-packages/Bard.py", line 63, in __init__
    self.async_chatbot = self.loop.run_until_complete(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/test/venv/lib/python3.11/site-packages/Bard.py", line 143, in create
    instance.SNlM0e = await instance.__get_snlm0e()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/test/venv/lib/python3.11/site-packages/Bard.py", line 196, in __get_snlm0e
    raise Exception(
Exception: Response code not 200. Response Status is 302

### ISSUE THREAD

**Issue by fakebhai** [armintum/Bard-Discord-bot#11]
![Screenshot_2023_0610_114109.jpg](https://github.com/armintum/Bard-Discord-bot/assets/101493467/aca1a7ef-7bdc-4ca3-a47e-58fc6a75d3bf)

This issue.

**Comment by fakebhai** [comment]
use the example code from README

result

>>> chatbot = Chatbot(token) Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/ubuntu/test/venv/lib/python3.11/site-packages/Bard.py", line 63, in __init__ self.async_chatbot = self.loop.run_until_complete( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "/home/ubuntu/test/venv/lib/python3.11/site-packages/Bard.py", line 143, in create instance.SNlM0e = await instance.__get_snlm0e() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/ubuntu/test/venv/lib/python3.11/site-packages/Bard.py", line 196, in __get_snlm0e raise Exception( Exception: Response code not 200. Response Status is 302

**Comment by plon** [comment]
It is caused by an invalid token
