### ISSUE TITLE
couldn't generate a response 

### ISSUE THREAD

**Issue by void6670** [armintum/Bard-Discord-bot#13]
so i thought i would give it a shot but as soon as I started testing the bot it just keeps giving me this error below and it also says "i couldn't generate a response" and then some random letters (i think they are not random tho but they are just the couldn't generate a response error

**Comment by void6670** [comment]
![Screenshot_2023-06-20-19-19-10-612-edit_com android chrome](https://github.com/armintum/Bard-Discord-bot/assets/106617191/4b7841b7-69ce-429b-8544-a90fcf831c8d)

**Comment by void6670** [comment]
![Screenshot_2023-06-20-19-18-53-739-edit_com aliucord](https://github.com/armintum/Bard-Discord-bot/assets/106617191/03885fa4-e306-4292-b6fb-5a1df5edd2a1)
this is what the bot says

**Comment by Jaicraft** [comment]
> so i thought i would give it a shot but as soon as I started testing the bot it just keeps giving me this error below and it also says "i couldn't generate a response" and then some random letters (i think they are not random tho but they are just the couldn't generate a response error

I think it had something do do with the Bard api required version being raised, since the most recent update completely made it unusable for me.

**Comment by void6670** [comment]
so can i do anything to fix it?

**Comment by Jaicraft** [comment]
> so can i do anything to fix it?

Idk

**Comment by Jaicraft** [comment]
Last time it worked the version was 1.1.3 I think

**Comment by Jaicraft** [comment]
You could also try not having a required version at all

**Comment by void6670** [comment]
alright ty
