### ISSUE TITLE
Request to be able to restrict commands like  /public, /private, /toggledm, /toggleactive,  /togglechannel to a list of userids and/or roleids

### ISSUE THREAD

**Issue by revblueldd** [armintum/Bard-Discord-bot#6]
It would be really cool if we could put a list of IDs in the .env file that control which users and/or roles are allowed to execute those commands.

**Comment by plon** [comment]
This can be done through server settings and then the integrations tab

**Comment by revblueldd** [comment]
Ah I forgot about that - thank you!
