### ISSUE TITLE
Returned message format

### ISSUE THREAD

**Issue by AndrewsPanda** [armintum/Bard-Discord-bot#8]
Thank you for this project! It's a great bot.

I have an issue request. The return message from bard is coming through as one long paragraph. Example below.

Can it please be formatted to return the message in paragraph format?

![image](https://github.com/armintum/Bard-Discord-bot/assets/1265156/82cd9ae7-cf4e-41c0-b901-3c5b686f285a)

**Comment by plon** [comment]
Bullet points should be formatted now.
