### ISSUE TITLE
Remove the bot token!

### ISSUE THREAD

**Issue by ghost** [armintum/Bard-Discord-bot#9]
Remove it dude!

**Comment by Jaicraft** [comment]
Wdym I don't see any token in there

**Comment by plon** [comment]
> Wdym I don't see any token in there

This guy thought the token in the readme was active...

**Comment by Ruu3f** [comment]
> > Wdym I don't see any token in there
> 
> This guy thought the token in the readme was active...

oh... should have ran a bot on it before making an issue 💀

**Comment by ghost** [comment]
> > Wdym I don't see any token in there
> 
> This guy thought the token in the readme was active...

Oh... I should've tested the token before making an issue, sorry for the misunderstanding.

**Comment by L4CTOSE** [comment]
Why the hell I received a email about this
